Andrej-sv81/UberApp_Tim26_ISS

.gitignore
Tim26-ISS/src/main/java/com/example/demo/controller/PassengerController.java
Tim26-ISS/src/main/java/com/example/demo/dto/DriverRideOverDTO.java
Tim26-ISS/src/main/java/com/example/demo/dto/MultiplePassengersDTO.java
Tim26-ISS/src/main/java/com/example/demo/dto/PassengerRequestDTO.java
Tim26-ISS/src/main/java/com/example/demo/dto/PassengerResponseDTO.java
Tim26-ISS/src/main/java/com/example/demo/dto/PassengerRideOverDTO.java
Tim26-ISS/src/main/java/com/example/demo/dto/PassengerRidesDTO.java
Tim26-ISS/src/main/java/com/example/demo/repository/InMemoryPassengerRepository.java
Tim26-ISS/src/main/java/com/example/demo/repository/PassengerRepository.java
Tim26-ISS/src/main/java/com/example/demo/service/PassengerService.java
Tim26-ISS/src/main/java/com/example/demo/service/PassengerServiceImpl.java

Metode za KT1 mrs

---

Tim26-ISS/src/main/java/com/example/demo/controller/DriverController.java
Tim26-ISS/src/main/java/com/example/demo/dto/DriverMultipleDocsResponseDTO.java

Get multiply documents of driver by id

Get documents

---

Tim26-ISS/src/main/java/com/example/demo/controller/DriverController.java

Adding new document for driver by id

Driver add new doc

---

Tim26-ISS/src/main/java/com/example/demo/controller/DriverController.java

Deleting Drivers document by id

Delete drivers document

---

Tim26-ISS/src/main/java/com/example/demo/controller/DriverController.java
Tim26-ISS/src/main/java/com/example/demo/dto/DriverWorkingHoursDTO.java
Tim26-ISS/src/main/java/com/example/demo/model/WorkingHour.java

Added WorkHours POJO class and method for getting all drivers working hours

Get drivers work hours

---

Tim26-ISS/src/main/java/com/example/demo/controller/DriverController.java

Added new method for posting working hours

Post new working hour

---

Tim26-ISS/src/main/java/com/example/demo/controller/DriverController.java

Get details about working hour of one driver

Get details about working hour

---

Tim26-ISS/src/main/java/com/example/demo/controller/DriverController.java
Tim26-ISS/src/main/java/com/example/demo/controller/PassengerController.java

Added method for updating working hour for one driver

Updating working hour

---

Tim26-ISS/src/main/java/com/example/demo/controller/UserController.java
Tim26-ISS/src/main/java/com/example/demo/dto/MultipleUsersDTO.java
Tim26-ISS/src/main/java/com/example/demo/dto/UserBlockDTO.java
Tim26-ISS/src/main/java/com/example/demo/dto/UserLoginDTO.java
Tim26-ISS/src/main/java/com/example/demo/dto/UserMessageRequestDTO.java
Tim26-ISS/src/main/java/com/example/demo/dto/UserMessageResponseDTO.java
Tim26-ISS/src/main/java/com/example/demo/dto/UserNoteRequestDTO.java
Tim26-ISS/src/main/java/com/example/demo/dto/UserNoteResponseDTO.java
Tim26-ISS/src/main/java/com/example/demo/dto/UserRequestDTO.java
Tim26-ISS/src/main/java/com/example/demo/dto/UserResponseDTO.java
Tim26-ISS/src/main/java/com/example/demo/dto/UserRidesDTO.java
Tim26-ISS/src/main/java/com/example/demo/dto/UserUnblockDTO.java
Tim26-ISS/src/main/java/com/example/demo/model/User.java
Tim26-ISS/src/main/java/com/example/demo/repository/InMemoryUserRepository.java
Tim26-ISS/src/main/java/com/example/demo/repository/UserRepository.java
Tim26-ISS/src/main/java/com/example/demo/service/UserService.java
Tim26-ISS/src/main/java/com/example/demo/service/UserServiceImpl.java

User model

---

Tim26-ISS/src/main/java/com/example/demo/controller/DriverController.java
Tim26-ISS/src/main/java/com/example/demo/dto/DriverVehicleRequestDTO.java
Tim26-ISS/src/main/java/com/example/demo/dto/DriverVehicleResponseDTO.java
Tim26-ISS/src/main/java/com/example/demo/model/Location.java
Tim26-ISS/src/main/java/com/example/demo/model/Vehicle.java

Added POJO classes and method for getting drivers info

Cu 33t7r60 administrator eli da vidi podatke o vozilu vozaca danilo babic

---

Tim26-ISS/src/main/java/com/example/demo/controller/DriverController.java

Added method for adding new vehicle for driver

Add new vehicle for driver

---

Tim26-ISS/src/main/java/com/example/demo/controller/DriverController.java

Added method for updating drivers vehicle

Updating drivers vehicle

---

Tim26-ISS/src/main/java/com/example/demo/controller/DriverController.java
Tim26-ISS/src/main/java/com/example/demo/controller/PassengerController.java
Tim26-ISS/src/main/java/com/example/demo/controller/RideController.java
Tim26-ISS/src/main/java/com/example/demo/dto/LocationDTO.java
Tim26-ISS/src/main/java/com/example/demo/dto/RideRequestDTO.java
Tim26-ISS/src/main/java/com/example/demo/dto/RouteDTO.java
Tim26-ISS/src/main/java/com/example/demo/service/RideService.java
Tim26-ISS/src/main/java/com/example/demo/service/RideServiceImpl.java

Added POJO and DTO classes for ride and fixed methods for passenger and driver

POJO and bug fixes

---

Tim26-ISS/src/main/java/com/example/demo/controller/RideController.java
Tim26-ISS/src/main/java/com/example/demo/dto/RideRequestDTO.java
Tim26-ISS/src/main/java/com/example/demo/dto/RideResponseDTO.java

Added post method for creating a ride

Added create ride

---

Tim26-ISS/src/main/java/com/example/demo/controller/RideController.java

Added get method for active ride for driver

Active ride for driver

---

Tim26-ISS/src/main/java/com/example/demo/controller/RideController.java
Tim26-ISS/src/main/java/com/example/demo/dto/RideResponseDTO.java

Added two get methods. One is for passenger other is for ride details

Ride info for passenger and ride id

---

Tim26-ISS/src/main/java/com/example/demo/controller/RideController.java

Added method for canceling ride without explanation

Cancel ride

---

Tim26-ISS/src/main/java/com/example/demo/controller/RideController.java
Tim26-ISS/src/main/java/com/example/demo/dto/ExplanationDTO.java

Added methods for accept ride and panic

Accept and panic procedure

---

Tim26-ISS/src/main/java/com/example/demo/controller/ReviewController.java
Tim26-ISS/src/main/java/com/example/demo/dto/MultipleReviewsDTO.java

Get seperate reviews for driver and vehicle

Driver and vehicle reviews

---

Tim26-ISS/src/main/java/com/example/demo/controller/ReviewController.java
Tim26-ISS/src/main/java/com/example/demo/dto/OneRideAllReviewsDTO.java

Review for driver and vehicle.

All reviews for one ride

---

Tim26-ISS/src/main/java/com/example/demo/controller/DriverController.java
Tim26-ISS/src/main/java/com/example/demo/dto/DriverVehicleRequestDTO.java
Tim26-ISS/src/main/java/com/example/demo/dto/DriverVehicleResponseDTO.java
Tim26-ISS/src/main/java/com/example/demo/model/Message.java
Tim26-ISS/src/main/java/com/example/demo/model/MessageType.java
Tim26-ISS/src/main/java/com/example/demo/model/Ride.java
Tim26-ISS/src/main/java/com/example/demo/model/UserActivation.java
Tim26-ISS/src/main/java/com/example/demo/model/Vehicle.java
Tim26-ISS/src/main/java/com/example/demo/model/VehicleType.java
Tim26-ISS/src/main/java/com/example/demo/model/VehicleTypeEnum.java
Tim26-ISS/src/main/java/com/example/demo/model/Warning.java
Tim26-ISS/src/main/java/com/example/demo/model/WorkingHour.java
Tim26-ISS/src/main/java/com/example/demo/repository/MessageRepository.java
Tim26-ISS/src/main/java/com/example/demo/repository/UserActivationRepository.java
Tim26-ISS/src/main/java/com/example/demo/repository/VehicleRepository.java
Tim26-ISS/src/main/java/com/example/demo/repository/WarningRepository.java
Tim26-ISS/src/main/java/com/example/demo/repository/WorkingHourRepository.java
Tim26-ISS/src/main/java/com/example/demo/service/MessageService.java
Tim26-ISS/src/main/java/com/example/demo/service/UserActivationService.java
Tim26-ISS/src/main/java/com/example/demo/service/VehicleService.java
Tim26-ISS/src/main/java/com/example/demo/service/WarningService.java
Tim26-ISS/src/main/java/com/example/demo/service/WorkingHourService.java

Completed models and repositories for the database

Completed models and repositories for the database
